In [15]:
import pandas as pd
from sqlalchemy import create_engine

In [26]:
mvp_file ="NBA Finals and MVP.xlsx"
mvp_df = pd.read_excel(mvp_file)
mvp_df

,Year,Western Champion,Eastern Champion,Result,NBA Champion,NBA Vice-Champion,Final Sweep ?,MVP Frist_Name,MVP Last_Name,MVP Height (m),MVP Height (ft),MVP Position,MVP Team,MVP Nationality,MVP status
0,1950,Minneapolis Lakers,Syracuse Nationals,4–2,Minneapolis Lakers,Syracuse Nationals,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1951,Rochester Royals,New York Knicks,4–3,Rochester Royals,New York Knicks,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1952,Minneapolis Lakers,New York Knicks,4–3,Minneapolis Lakers,New York Knicks,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1953,Minneapolis Lakers,New York Knicks,4–1,Minneapolis Lakers,New York Knicks,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1954,Minneapolis Lakers,Syracuse Nationals,4–3,Minneapolis Lakers,Syracuse Nationals,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,2014,San Antonio Spurs,Miami Heat,4–1,San Antonio Spurs,Miami Heat,False,Kevin,Durant,2.06,6.758530,Forward,Oklahoma City Thunder,US,Not reached Final
65,2015,Golden State Warriors,Cleveland Cavaliers,4–2,Golden State Warriors,Cleveland Cavaliers,False,Stephen,Curry,1.91,6.266404,Guard,Golden State Warriors,US,Champion
66,2016,Golden State Warriors,Cleveland Cavaliers,4–3,Cleveland Cavaliers,Golden State Warriors,False,Stephen,Curry,1.91,6.266404,Guard,Golden State Warriors,US,Vice-Champion
67,2017,Golden State Warriors,Cleveland Cavaliers,4-2,Golden State Warriors,Cleveland Cavaliers,False,Russell,Westbrook,1.91,6.266404,Guard,Oklahoma City Thunder,US,Not reached Final
68,2018,Golden State Warriors,Cleveland Cavaliers,4-0,Golden State Warriors,Cleveland Cavaliers,True,James,Harden,1.96,6.500000,Guard,Houston Rockets,US,Not reached Final

In [18]:
df_drop=mvp_df.iloc[6:]
df_drop

,Year,Western Champion,Eastern Champion,Result,NBA Champion,NBA Vice-Champion,Final Sweep ?,MVP Frist_Name,MVP Last_Name,MVP Height (m),MVP Height (ft),MVP Position,MVP Team,MVP Nationality,MVP status
6,1956,Fort Wayne Pistons,Philadelphia Warriors,1–4,Philadelphia Warriors,Fort Wayne Pistons,False,Bob,Pettit,2.06,6.758530,Forward,Saint Louis Hawks,US,Not reached Final
7,1957,St. Louis Hawks,Boston Celtics,3–4,Boston Celtics,St. Louis Hawks,False,Bob,Cousy,1.85,6.069554,Guard,Boston Celtics,US,Champion
8,1958,St. Louis Hawks,Boston Celtics,4–2,St. Louis Hawks,Boston Celtics,False,Bill,Russell,2.08,6.824147,Center,Boston Celtics,US,Vice-Champion
9,1959,Minneapolis Lakers,Boston Celtics,0–4,Boston Celtics,Minneapolis Lakers,True,Bob,Pettit,2.06,6.758530,Forward,Saint Louis Hawks,US,Not reached Final
10,1960,St. Louis Hawks,Boston Celtics,3–4,Boston Celtics,St. Louis Hawks,False,Wilt,Chamberlain,2.16,7.086614,Center,Philadelphia Warriors,US,Not reached Final
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,2014,San Antonio Spurs,Miami Heat,4–1,San Antonio Spurs,Miami Heat,False,Kevin,Durant,2.06,6.758530,Forward,Oklahoma City Thunder,US,Not reached Final
65,2015,Golden State Warriors,Cleveland Cavaliers,4–2,Golden State Warriors,Cleveland Cavaliers,False,Stephen,Curry,1.91,6.266404,Guard,Golden State Warriors,US,Champion
66,2016,Golden State Warriors,Cleveland Cavaliers,4–3,Cleveland Cavaliers,Golden State Warriors,False,Stephen,Curry,1.91,6.266404,Guard,Golden State Warriors,US,Vice-Champion
67,2017,Golden State Warriors,Cleveland Cavaliers,4-2,Golden State Warriors,Cleveland Cavaliers,False,Russell,Westbrook,1.91,6.266404,Guard,Oklahoma City Thunder,US,Not reached Final
68,2018,Golden State Warriors,Cleveland Cavaliers,4-0,Golden State Warriors,Cleveland Cavaliers,True,James,Harden,1.96,6.500000,Guard,Houston Rockets,US,Not reached Final

In [21]:
new_mvp_df =df_drop[['MVP Frist_Name', 'MVP Last_Name','Year','MVP Position','MVP Team','MVP Nationality','MVP status']].copy()
new_mvp_df.head()

,MVP Frist_Name,MVP Last_Name,Year,MVP Position,MVP Team,MVP Nationality,MVP status
6,Bob,Pettit,1956,Forward,Saint Louis Hawks,US,Not reached Final
7,Bob,Cousy,1957,Guard,Boston Celtics,US,Champion
8,Bill,Russell,1958,Center,Boston Celtics,US,Vice-Champion
9,Bob,Pettit,1959,Forward,Saint Louis Hawks,US,Not reached Final
10,Wilt,Chamberlain,1960,Center,Philadelphia Warriors,US,Not reached Final

In [22]:
mvp = new_mvp_df.rename(columns={                                
                                 "MVP Position": "MVP_Position",
                                 "MVP Team": "MVP_team",
                                "MVP Nationality":"MVP_nationality",
                                 "MVP status":"MVP_status"
                                })
mvp.head()

,MVP Frist_Name,MVP Last_Name,Year,MVP_Position,MVP_team,MVP_nationality,MVP_status
6,Bob,Pettit,1956,Forward,Saint Louis Hawks,US,Not reached Final
7,Bob,Cousy,1957,Guard,Boston Celtics,US,Champion
8,Bill,Russell,1958,Center,Boston Celtics,US,Vice-Champion
9,Bob,Pettit,1959,Forward,Saint Louis Hawks,US,Not reached Final
10,Wilt,Chamberlain,1960,Center,Philadelphia Warriors,US,Not reached Final

In [ ]:
team =

In [23]:
connection = "postgres:root123@localhost:5432/NBAdatabase"
engine = create_engine(f'postgresql://{connection}')

In [24]:
engine.table_names()

['player_stats_2017',
 'player_stats_2018',
 'mvp',
 'team',
 'hall_of_fame_player',
 'player',
 'player_stats_2016']

In [ ]:
# Uploading players information into Player_info table


mvp.to_sql('MVP_db', con = engine, if_exists = 'append', index = False)

In [42]:
team=pd.read_csv("Resources/TeamDetails.csv")
team

,team_id,abbreviation,team_name,year_founded,yearactive_till,arena_capacity
0,1610612737,ATL,Hawks,1949,present,18729
1,1610612737,ATL,Hawks,1949,present,18729
2,1610612738,BOS,Celtics,1946,present,18624
3,1610612739,CLE,Cavaliers,1970,present,20562
4,1610612740,NOP,Pelicans,2002,present,18000
5,1610612741,CHI,Bulls,1966,present,21711
6,1610612742,DAL,Mavericks,1980,present,21041
7,1610612743,DEN,Nuggets,1976,present,19099
8,1610612744,GSW,Warriors,1946,present,19596
9,1610612745,HOU,Rockets,1967,present,18300
10,1610612746,LAC,Clippers,1970,present,18997
11,1610612747,LAL,Lakers,1948,present,18997
12,1610612748,MIA,Heat,1988,present,19600
13,1610612749,MIL,Bucks,1968,present,18717
14,1610612750,MIN,Timberwolves,1989,present,20500
15,1610612751,BKN,Nets,1976,present,18103
16,1610612752,NYK,Knicks,1946,present,19763
17,1610612753,ORL,Magic,1989,present,18500
18,1610612754,IND,Pacers,1976,present,18165
19,1610612755,PHI,76ers,1949,present,21600
20,1610612756,PHX,Suns,1968,present,18422
21,1610612757,POR,Trail Blazers,1970,present,19980
22,1610612758,SAC,Kings,1948,present,17317
23,1610612759,SAS,Spurs,1976,present,18797
24,1610612760,OKC,Thunder,1967,present,18203
25,1610612761,TOR,Raptors,1995,present,19800
26,1610612762,UTA,Jazz,1974,present,19991
27,1610612763,MEM,Grizzlies,1995,present,21165
28,1610612764,WAS,Wizards,1961,present,20173
29,1610612765,DET,Pistons,1948,present,22076
30,1610612766,CHA,Hornets,1988,present,18103

In [37]:
test="Bulls"
for team_to_check in mvp['MVP_team']:
    for row_in_master_data in team['team_name']:
        if row_in_master_data in team_to_check:
            mvp['team_id']=team['team_id']

In [41]:
mvp.tail()

,MVP Frist_Name,MVP Last_Name,Year,MVP_Position,MVP_team,MVP_nationality,MVP_status,team_id
64,Kevin,Durant,2014,Forward,Oklahoma City Thunder,US,Not reached Final,NaN
65,Stephen,Curry,2015,Guard,Golden State Warriors,US,Champion,NaN
66,Stephen,Curry,2016,Guard,Golden State Warriors,US,Vice-Champion,NaN
67,Russell,Westbrook,2017,Guard,Oklahoma City Thunder,US,Not reached Final,NaN
68,James,Harden,2018,Guard,Houston Rockets,US,Not reached Final,NaN